# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicList', '0002_auto_20180429_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
